[package]
name = "llm_chain"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.91"
clap = { version = "4.5.20", features = ["derive"] }
dialoguer = "0.11.0"
llm-chain = "0.13.0"
llm-chain-openai = "0.13.0"
tokio = { version = "1.41.0", features = ["full"] }
