[package]
name = "rust_ai_simpleway"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.91"
clap = { version = "4.5.20", features = ["derive"] }
dialoguer = "0.11.0"
rust-bert = "=0.19.0"
tokio = { version = "1.41.0", features = ["full"] }
